site_name: YAPG − Modding documentation
pages:
    - Home: index.md
    - Templates: templates.md
    - Types and Components reference:
        - Native types: components/native-types.md
        - Components and classes: components/components.md
    - Lua functions reference: lua.md
