site_name: YAPG − Modding documentation
pages:
    - Home: index.md
    - Templates: templates.md
    - Lua/XML serialization:
        - Basic types: components/native-types.md
        - Utility classes: components/utility-classes.md
        - Components and classes: components/components.md
    - Lua runtime: lua.md
