site_name: YAPG − Modding documentation v0.3.0
theme: readthedocs
pages:
    - Home: index.md
    - Templates: templates.md
    - Lua/XML serialization: native-types.md
    - Components reference:
        - Components: components/components.md
        - Utility classes: components/utility-classes.md
    - Lua runtime: lua.md
